[package]
name = "tugger-wix"
version = "0.3.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Interfaces to the WiX Toolset to produce Windows installers"
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = "1.0"
duct = "0.13"
lazy_static = "1.4"
slog = "2.4"
url = "2.1"
uuid = { version = "0.8", features = ["v4", "v5"] }
xml-rs = "0.8"

[dependencies.tugger-common]
version = "0.3.0-pre"
path = "../tugger-common"

[dependencies.tugger-windows]
version = "0.3.0-pre"
path = "../tugger-windows"

[dependencies.tugger-file-manifest]
version = "0.3.0-pre"
path = "../tugger-file-manifest"

[dev-dependencies]
msi = "0.3"
tempdir = "0.3"
