[workspace]
members = [
    'oxidized-importer',
    'pyembed',
    'pyoxidizer',
    'python-packaging',
    'python-packed-resources',
    'release',
    'starlark-dialect-build-targets',
    'tugger',
    'virtual-file-manifest',
]
