[package]
name = "pyembed"
version = "0.8.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "Python-2.0 AND MPL-2.0"
description = "Embed a Python interpreter"
build = "build.rs"
# Adding this line enables DEP_* environment variables to be set in
# dependent crates. We rely on this to allow crates embedding this one
# to access the artifacts we build.
links = "pythonXY"

[dependencies]
# Update documentation in lib.rs when new dependencies are added.
anyhow = "1.0"
cpython = { git = "https://github.com/indygreg/rust-cpython.git", rev = "e1b18aaae2f7ca2dda1edbd5270b6d1d25c01d7d" }
jemalloc-sys = { version = "0.3", optional = true }
lazy_static = "1.4"
libc = "0.2"
python3-sys = { git = "https://github.com/indygreg/rust-cpython.git", rev = "e1b18aaae2f7ca2dda1edbd5270b6d1d25c01d7d" }
python-packed-resources = { version = "0.2.0-pre", path = "../python-packed-resources" }
uuid = { version = "0.8", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
memory-module-sys = "0.3"
winapi = { version = "0.3", features = ["libloaderapi", "memoryapi", "minwindef"] }

[features]
default = ["build-mode-standalone", "cpython-link-unresolved-static"]
jemalloc = ["jemalloc-sys"]

# Build this crate in isolation, without using PyOxidizer.
build-mode-standalone = []

# Build this crate by executing a `pyoxidizer` executable to build
# required artifacts.
build-mode-pyoxidizer-exe = []

# Build this crate by reusing artifacts generated by `pyoxidizer` out-of-band.
# In this mode, the PYOXIDIZER_ARTIFACT_DIR environment variable can refer
# to the directory containing build artifacts produced by `pyoxidizer`. If not
# set, OUT_DIR will be used.
build-mode-prebuilt-artifacts = []

# Build mode for running tests.
build-mode-test = [
    "cpython-link-default",
]

# Build the cpython crate in unresolved static mode (we will provide a static
# library to link against).
cpython-link-unresolved-static = [
    "cpython/py-link-mode-unresolved-static",
    "cpython/python3-sys",
    "cpython/no-auto-initialize",
]

# Build the cpython with default link mode control. It will pick up the prebuilt
# libpython from PYTHON_SYS_EXECUTABLE or from PATH.
cpython-link-default = [
    "cpython/py-link-mode-default",
    "cpython/python3-sys",
    "cpython/no-auto-initialize",
]
