[package]
name = "pyembed"
version = "0.6.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "Python-2.0 AND MPL-2.0"
build = "build.rs"
# Adding this line enables DEP_* environment variables to be set in
# dependent crates. We rely on this to allow crates embedding this one
# to access the artifacts we build.
links = "pythonXY"

[dependencies]
# Update documentation in lib.rs when new dependencies are added.
byteorder = "1"
cpython = { version = "0.4", features = ["py-link-mode-unresolved-static", "python3-sys", "no-auto-initialize"]}
jemalloc-sys = { version = "0.3", optional = true }
lazy_static = "1.4"
libc = "0.2"
python3-sys = "0.4"
uuid = { version = "0.8", features = ["v4"] }

[features]
default = ["build-mode-standalone"]
jemalloc = ["jemalloc-sys"]

# Build this crate in isolation, without using PyOxidizer.
build-mode-standalone = []

# Build this crate by executing a `pyoxidizer` executable to build
# required artifacts.
build-mode-pyoxidizer-exe = []

# Build this crate by reusing artifacts generated by `pyoxidizer` out-of-band.
# In this mode, the PYOXIDIZER_ARTIFACT_DIR environment variable can refer
# to the directory containing build artifacts produced by `pyoxidizer`. If not
# set, OUT_DIR will be used.
build-mode-prebuilt-artifacts = []
