[package]
name = "pyembed"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
pyrepackager = { path = "../pyrepackager" }

[dependencies]
byteorder = "1"
libc = "0.2"
python3-sys = { path = "../third_party/rust-cpython/python3-sys" }
uuid = { version = "0.7", features = ["v4"] }

[dependencies.cpython]
path = "../third_party/rust-cpython"
features = ["link-mode-unresolved-static", "python3-sys", "no-auto-initialize"]
