[package]
name = "pyembed"
version = "0.5.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "Python-2.0 AND MPL-2.0"
build = "build.rs"

[build-dependencies]
pyoxidizer = { path = "../pyoxidizer" }
slog = "2.4"

[dependencies]
# Update documentation in lib.rs when new dependencies are added.
byteorder = "1"
jemalloc-sys = { version = "0.3", optional = true }
libc = "0.2"
python3-sys = { git = "https://github.com/dgrunwald/rust-cpython", rev = "a989865c3dd861267a42ceb726f2fc831637fe5b" }
uuid = { version = "0.8", features = ["v4"] }

[dependencies.cpython]
git = "https://github.com/dgrunwald/rust-cpython"
rev = "a989865c3dd861267a42ceb726f2fc831637fe5b"
features = ["py-link-mode-unresolved-static", "python3-sys", "no-auto-initialize"]

[features]
default = ["jemalloc-sys"]
