[package]
name = "pyembed"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1"
jemalloc-sys = { version = "0.3", optional = true }
libc = "0.2"
uuid = { version = "0.7", features = ["v4"] }

[dependencies.python3-sys]
{{~#if pyoxidizer_git_url}}
git = "{{{ pyoxidizer_git_url }}}"
rev = "{{{pyoxidizer_git_commit}}}"
{{else}}
path = "{{{ pyoxidizer_local_repo_path }}}/third_party/rust-cpython/python3-sys"
{{~/if}}
[dependencies.cpython]
{{~#if pyoxidizer_git_url}}
git = "{{{ pyoxidizer_git_url }}}"
rev = "{{{pyoxidizer_git_commit}}}"
{{else}}
path = "{{{ pyoxidizer_local_repo_path }}}/third_party/rust-cpython"
{{/if~}}
features = ["link-mode-unresolved-static", "python3-sys", "no-auto-initialize"]

[features]
default = []
jemalloc = ["jemalloc-sys"]
