[package]
name = "pyembed"
version = "0.6.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1"
cpython = { version = "0.4", features = ["py-link-mode-unresolved-static", "python3-sys", "no-auto-initialize"]}
jemalloc-sys = { version = "0.3", optional = true }
lazy_static = "1.4"
libc = "0.2"
python3-sys = "0.4"
uuid = { version = "0.8", features = ["v4"] }

[features]
default = []
jemalloc = ["jemalloc-sys"]
