[package]
name = "pyoxidizer"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
byteorder = "1.2"
cargo_toml = "0.6"
cc = "1.0"
clap = "2.32"
git2 = "0.8"
glob = "0.3"
goblin = "0.0"
handlebars = "1.1"
hex = "0.3"
itertools = "0.8"
lazy_static = "1.2"
libc = "0.2"
regex = "1"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8"
tar = "0.4"
tempdir = "0.3"
toml = "0.4"
url = "1.7"
version-compare = "0.0"
walkdir = "2"
zstd = "0.4"
