[package]
name = "tugger-debian"
version = "0.8.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Debian packaging primitives"
keywords = ["debian", "package", "tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
ar = "0.9"
chrono = "0.4"
digest = "0.9"
libflate = "1.0"
mailparse = "0.13"
md-5 = "0.9"
os_str_bytes = "5.0"
pgp = "0.7"
sha-1 = "0.9"
sha2 = "0.9"
tar = "0.4"
thiserror = "1.0"
xz2 = "0.1"
zstd = "0.9"

[dependencies.tugger-file-manifest]
version = "0.7.0-pre"
path = "../tugger-file-manifest"

[dev-dependencies]
anyhow = "1.0"
glob = "0.3"
