[package]
name = "tugger-debian"
version = "0.8.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Debian packaging primitives"
keywords = ["debian", "package", "tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
ar = "0.9"
chrono = "0.4"
digest = "0.9"
hex = "0.4"
libflate = "1.0"
mailparse = "0.13"
md-5 = "0.9"
once_cell = "1.8"
os_str_bytes = "5.0"
pgp = "0.7"
regex = "1.5"
sha-1 = "0.9"
sha2 = "0.9"
tar = "0.4"
thiserror = "1.0"
url = "2.2"
xz2 = "0.1"
zstd = "0.9"

[dependencies.async-compression]
version = "0.3"
optional = true
features = ["bzip2", "futures-io", "gzip", "lzma", "xz"]

[dependencies.async-trait]
version = "0.1"
optional = true

[dependencies.futures]
version = "0.3"
optional = true

[dependencies.reqwest]
version = "0.11"
optional = true
default-features = false
features = ["rustls-tls", "stream"]

[dependencies.tokio]
version = "1.14"
optional = true
features = ["macros"]

[dependencies.tugger-file-manifest]
version = "0.7.0-pre"
path = "../tugger-file-manifest"

[dev-dependencies]
anyhow = "1.0"
glob = "0.3"
indoc = "1.0"

[features]
default = ["async", "http"]
async = ["async-compression", "async-trait", "futures"]
http = ["async", "reqwest", "tokio"]
