[package]
name = "tugger-apple-codesign"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Pure Rust interface to code signing on Apple platforms"
keywords = ["tugger", "apple", "macos", "codesign"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[[bin]]
name = "rcodesign"
path = "src/main.rs"

[dependencies]
clap = "2.33"
digest = "0.9"
goblin = "0.3"
pem = "0.8"
scroll = "0.10"
sha-1 = "0.9"
sha2 = "0.9"

[dev-dependencies.cryptographic-message-syntax]
path = "../cryptographic-message-syntax"
version = "0.1.0-dev"
