[package]
name = "tugger-code-signing"
version = "0.7.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Cross-platform code signing functionality"
keywords = ["tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
anyhow = "1.0"
bcder = "0.6"
goblin = "0.5"
p12 = "0.6"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
slog = "2.7"
tempfile = "3.2"
thiserror = "1.0"
yasna = "0.5"

[dependencies.apple-bundles]
version = "0.9.0-pre"
path = "../apple-bundles"

[dependencies.apple-codesign]
version = "0.11.0-pre"
path = "../apple-codesign"

[dependencies.cryptographic-message-syntax]
version = "0.14.0"
# path = "../cryptographic-message-syntax"

[dependencies.tugger-file-manifest]
version = "0.8.0-pre"
path = "../tugger-file-manifest"

[dependencies.tugger-windows-codesign]
version = "0.8.0-pre"
path = "../tugger-windows-codesign"

[dependencies.x509-certificate]
version = "0.12.0"
# path = "../x509-certificate"
