[package]
name = "tugger-code-signing"
version = "0.1.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Cross-platform code signing functionality"
keywords = ["tugger"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[dependencies]
bcder = "0.6"
goblin = "0.4"
p12 = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
thiserror = "1.0"
yasna = "0.3"

[dependencies.cryptographic-message-syntax]
version = "0.2.0-pre"
path = "../cryptographic-message-syntax"

[dependencies.tugger-apple-bundle]
version = "0.3.0-pre"
path = "../tugger-apple-bundle"

[dependencies.tugger-apple-codesign]
version = "0.3.0-pre"
path = "../tugger-apple-codesign"

[dependencies.tugger-windows-codesign]
version = "0.3.0-pre"
path = "../tugger-windows-codesign"
