[package]
name = "release"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
description = "Performs a release of PyOxidizer"
license = "MPL-2.0"
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"

[dependencies]
anyhow = "1"
bytes = "1"
cargo-lock = "7"
cargo_toml = "0"
clap = "3"
dirs = "4"
duct = "0"
futures = "0"
# We don't need network functionality.
git2 = { version = "0", default-features = false }
hex = "0"
maturin = "0"
octocrab = { version = "0", default-features = false, features = ["rustls"] }
once_cell = "1"
reqwest = {version = "0", default-features = false, features = ["rustls"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0"
tempfile = "3"
tokio = "1"
toml = "0"
url = "2"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
