[package]
name = "release"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
description = "Performs a release of PyOxidizer"
license = "MPL-2.0"
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"

[dependencies]
anyhow = "1.0"
cargo_toml = "0.8"
clap = "2.33"
duct = "0.13"
# We don't need network functionality.
git2 = { version = "0.13", default-features = false }
lazy_static = "1.4"
semver = "0.11"
toml = "0.5"
