[package]
name = "tugger"
version = "0.3.0-pre"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Package and distribute applications"
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"
build = "build.rs"

[dependencies]
anyhow = "1.0"
ar = "0.8"
chrono = "0.4"
codemap = "0.1"
codemap-diagnostic = "0.1"
duct = "0.13"
fs2 = "0.4"
glob = "0.3"
hex = "0.4"
lazy_static = "1.4"
libflate = "1.0"
md5 = "0.7"
os_str_bytes = "2.3"
reqwest = { version = "0.10", default-features= false, features = ["blocking", "rustls-tls"] }
semver = "0.11"
serde_yaml = "0.8"
serde = "1.0"
sha2 = "0.9"
slog = "2.4"
starlark = "0.3.1"
tar = "0.4"
url = "2.1"
uuid = { version = "0.8", features = ["v4", "v5"] }
version-compare = "0.0"
walkdir = "2"
xml-rs = "0.8"
xz2 = "0.1"
zip = "0.5"
zstd = "0.5"

[target.'cfg(unix)'.dependencies]
# Create doesn't build on Windows. https://github.com/Richterrettich/rpm-rs/pull/30 fixes.
rpm-rs = "0.6"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["combaseapi", "knownfolders", "shlobj", "shtypes"] }

[dependencies.starlark-dialect-build-targets]
version = "0.2.0-pre"
path = "../starlark-dialect-build-targets"

[dependencies.virtual-file-manifest]
version = "0.1.0-pre"
path = "../virtual-file-manifest"

[dev-dependencies]
msi = "0.3"
tempdir = "0.3"
