on:
  push:
  pull_request:
  schedule:
    - cron: '13 4 * * *'
jobs:
  pyembed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: "--manifest-path pyembed/Cargo.toml"
