on:
  push:
  pull_request:
  schedule:
    - cron: '13 15 * * *'
jobs:
  sphinx:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - python-oxidized-importer/docs
          - pyembed/docs
          - tugger/docs
          - docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run Sphinx
        run: |
          python3.9 -m pip install Sphinx==3.5.3
          make -C ${{ matrix.dir }} html
